name: Build & Publish
on:
    release:
      types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update Version
      id: semver
      uses: RightBrain-Networks/semver-action@master
      with:
        mode: get
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build
      run: |
        python setup.py sdist bdist_wheel
    - name: PyPi Publish
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
